local/templates/aspro_kshop_copy/components/bitrix/news.list/news_slider/template.php
local/templates/aspro_kshop_copy/components/bitrix/news.list/slide_home/script.js
local/templates/aspro_kshop_copy/components/bitrix/news.list/slide_home/style.css
local/templates/aspro_kshop_copy/components/bitrix/news.list/slide_home/template.php

SUP-4280: edit slider

---

local/php_interface/init.php

создание папки и размещение в него .config.php

SUP:4280 create derectory

---

css/opt_plans_pages.css

SUP-4386: edit styles

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/props.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/props_format.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/style.css

изменение сортировки полей заказа

SUP-4411:  edit sort string in order

---

local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.detail/shop/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.list/orders/template.php
local/templates/shaveclub_personal/header.php

блокировка кнопки при определенных статусах заказа

Sup 4412: lock the button for the status of the order

---

css/opt_plans_pages.css

SUP-4386: edit style

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/confirm.php

корректировка вывода адреса доставки

SUP-4411: edit file commit.php

---

local/templates/aspro_kshop_copy/components/bitrix/news.list/main_template/template.php

удаление даты активности новости

SUP-4480: deleted date active

---

ajax/checkEmail.php
ajax/checkForm.php
ajax/form_result_new.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/props_format.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/template.php

запись полей заказа в сессию и вывод после авторизации

SUP-4387: Order entry fields in the session and concluded after login

---

css/responsive.css

SIP-4450 edit style

---

css/responsive.css

SUP-4450: edit

---

local/php_interface/s2/init.php

SUP-4453: replacing letters sent events

---

local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/main/script.js

Изменение преобразования дробных сумм для корректности преобразования суммы при изменении количества товара (из parseInt в parseFloat с использованием .replace и .toFixed). Работа по кодстайлу.

SUP-4468: Fixing animated price changing on the basket page

---

ajax/checkEmail.php

SUP-4504: change encoding

---

local/php_interface/s2/init.php

изменение события OnBeforeEventSend

SUP-4496: OnBeforeEventSend change events

---

local/templates/aspro_kshop_copy/components/bitrix/system.auth.changepasswd/change/template.php
local/templates/aspro_kshop_copy/components/bitrix/system.auth.forgotpasswd/forgot/template.php

изменение условия при восстановлении пароля

SUP-4496: changing conditions for password recovery

---

local/php_interface/s2/init.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly/script.js
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/main/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php

Работа над кодстайлом в шаблоне "малой корзины" и в шаблоне оформления заказа, доработка вёрстки оформления заказа. (редактирование поля службы доставки в summary.php и добавление поля "Способ оплаты")

SUP-4543: fixing codestyle at flying basket template and order making template, fixing order making template layout

---

local/php_interface/init.php

Код блокировки удаление визуального редактора

SUP-4582: Lock code removing the visual editor

---

local/templates/aspro_kshop_copy/components/bitrix/news.list/slide_home/script.js

Редактирование JS-скрипта, отвечающего за переключение кнопок слайдов новостей и акций. Настройка переадресации на соответствующие ссылки после нажатия на кнопку, отвечающую за активный слайд.

SUP-4580: fixing script for redirecting after pushing the active slides' buttons

---

local/templates/shaveclub_index/header.php

SUP-4583: edit index file

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/props_format.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/style.css

SUP-4619: changes in the index field

---

.bottom_lk.menu.php
css/jquery.jscrollpane.css
local/templates/shaveclub_inner_without_footer/footer.php
local/templates/shaveclub_inner_without_footer/styles.css
local/templates/shaveclub_item_card/footer.php
local/templates/shaveclub_item_card/styles.css
local/templates/shaveclub_personal/footer.php
local/templates/shaveclub_personal/header.php
local/templates/shaveclub_personal/styles.css

лобаление футера на страницы лк , и заказа

SUP-4583: append the footer to the pages of lk , and order

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/props_format.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/related_props.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/style.css
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/template.php

изменениие вывода дополнительного свойства

SUP-4628: Changing the Display of additional properties

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/props_format.php

добавление поля индекса в сессию

SUP-4628: add ZIP in session

---

local/php_interface/init.php

добавление условия на проверку склада по имени

SUP-4453: Adding a condition to check the warehouse named

---

local/php_interface/include/sale_payment/epages.pickpoint/.description.php
local/php_interface/include/sale_payment/epages.pickpoint/payment.php
local/php_interface/include/sale_payment/rficb.payment/.description.php
local/php_interface/include/sale_payment/rficb.payment/payment.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/confirm.php

SUP-4701: edit pay sistem

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/related_props.php

SUP-4619: edit input ZIP

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/related_props.php

SUP-4619: edit filr index

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/related_props.php

SUP-4628: edit index

---

css/opt_plans_pages.css

правка стилей для разрешения экрана 1366-768

SUP-4386: правка стилей для разрешения экрана 1366-768

---

local/php_interface/s1/init.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/confirm.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/delivery.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/props_format.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/style.css
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/template.php

правка финальной страницы заказа

SUP-4772: правка финальной страницы заказа

---

local/php_interface/s1/init.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/delivery.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/props_format.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/style.css
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/template.php

SUP-4628: правка поля индекса

---

ajax/coupon.php
local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/template.php

SUP-4769: правка промо кода 

---

auth/forgot-password/index.php
local/templates/aspro_kshop_copy/components/bitrix/system.auth.forgotpasswd/forgot/template.php

правка url восстановления пароля

SUP-4782: правка url восстановления пароля

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/template.php

SUP-4628: правка условия на вводимые символы в поле индекса

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/confirm.php

изменение плана бритья в файла confirm.php

SUP-4772: изменение плана бритья в файла confirm.php

---

local/php_interface/init.php

правки страницы восстановления пароля

SUP-4782: правки страницы восстановления пароля

---

local/php_interface/init.php
local/php_interface/s2/init.php

Перемещение скриптов по обработчикам смены статуса заказа, в зависимости от текущего сайта.

SUP-4546: перемещение скриптов по обработчикам

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/confirm.php

изменение условий на странице завершения заказа

SUP-4772: изменение условий на странице завершения заказа

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/confirm.php

правки по последней странице оформления заказа

SUP-4772: правки по последней странице оформления заказа

---

local/php_interface/init.php

Доработка функций в init.php, связанных с созданием отгрузок для заказов, с учетом смены статуса на "Сформирован".

SUP-4546: доработка функций по отгрузкам

---

local/php_interface/s2/init.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/style.css
local/templates/aspro_kshop_copy/components/bitrix/catalog.smart.filter/main/result_modifier.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.smart.filter/main/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog/main/section.php
local/templates/aspro_kshop_copy/css/styles.css

исправление в карточке товара и раздела каталога

SUP-5062: исправление в карточке товара и раздела каталога

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/template.php

SUP-5062: доработки в карточке товара

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/template.php

правки при отображении скидки в комплектах

SUP-5059: правки при отображении скидки в комплектах

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/result_modifier.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/template.php

добавление скидки на товары в комплекте

SUp-5059: добавление скидки на товары в комплекте

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/style.css
local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.section/catalog_block/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.section/catalog_block/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.section/catalog_list/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.section/catalog_list/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.section/viewed/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.section/viewed/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.top/front_slider/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.top/front_slider/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.top/specials_slider/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.top/specials_slider/template.php
local/templates/aspro_kshop_copy/css/colors.css
local/templates/aspro_kshop_copy/css/styles.css

изменение цвета и добавление валюты

SUP-5059: изменение цвета и добавление валюты 

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.section/viewed/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.top/specials_slider/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/catalog.top/specials_slider/result_modifier.php

добавление блоков на главную страницу

SUP-5097: добавление блоков на главную страницу

---

local/templates/aspro_kshop_copy/css/styles.css

изменение отображения скидки цены

SUP-5059: изменение отображения скидки цены

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.top/specials_slider/result_modifier.php

исправление блока на главной странице

SUP-5097: исправление блока на главной странице

---

local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly_order/template.php
local/templates/aspro_kshop_copy/footer.php
local/templates/aspro_kshop_copy/header.php

SUP-5099: изменение яндекс метрики

---

local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly/basket_items.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly_order/basket_items.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly_order/result_modifier.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly_order/script.js
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/main/basket_items.php

добавление знаков + и - в корзине

SUP-5096: добавление знаков + и - в корзине

---

local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly/basket_items.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly_order/basket_items.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/main/basket_items.php

удаление сообщения о не хватке элемента в корзине

SUP-5096: удаление сообщения о не хватке элемента в корзине

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.section/catalog_block/template.php

SUP-5059: добавление значков акций

---

local/templates/aspro_kshop_copy/css/styles.css

корректировка размеров элементов каталога

SUP-5062: корректировка размеров элементов каталога

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.element/main/template.php

изменение текста в блоке рекомендованных товаров

SUP-5061: изменение текста в блоке рекомендованных товаров

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.section/viewed/result_modifier.php
local/templates/aspro_kshop_copy/components/bitrix/catalog/main/section.php
local/templates/aspro_kshop_copy/css/styles.css

добавление количества выводимых элементов просмотренных товаров

SUP-5062: добавление количества выводимых элементов просмотренных товаров

---

local/templates/aspro_kshop_copy/components/bitrix/catalog.section/viewed/template.php

доработка блока просмотренных товаров

SUP-5062: доработка блока просмотренных товаров

---

local/php_interface/s1/init.php

добавление return в хендлер отправки письма

SUP-4875: добавление return в хендлер отправки письма

---

local/php_interface/init.php

добавление return в хендлер отправки письма

SUP-4875: удаление конфликтующего кода отправки письма

---

local/php_interface/init.php

удаление события пере затирающее письмо заказа

SUP-4875: удаление события пере затирающее письмо заказа

---

local/php_interface/init.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/delivery.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/template.php
local/templates/aspro_kshop_copy/css/styles.css

доработка вывода свойств заказа (поля, привязанные к службам доставки, выводятся сразу после выбранной службы)

SUP-5353: доработка вывода свойств заказа

---

local/php_interface/init.php

изменение ссылки картинки в письме

SUP-4875: изменение ссылки картинки в письме

---

local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.detail/shop/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.list/orders/template.php
local/templates/aspro_kshop_copy/template_styles.css

правки страницы личного кабинета

SUP-5728: правки страницы личного кабинета

---

local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.detail/shop/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.detail/shop/template.php
local/templates/aspro_kshop_copy/template_styles.css

изменение детальной страницы заказов пользователя

SUP-5728: изменение детальной страницы заказов пользователя

---

local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.detail/shop/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.list/orders/result_modifier.php
local/templates/aspro_kshop_copy/components/bitrix/sale.personal.order.list/orders/template.php

изменение сортировки и пвз заказов в лк

SUP-5728: изменение сортировки и пвз заказов в лк

---

local/php_interface/init.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/lang/ru/template.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/props_format.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/style.css
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/template.php

SUP-5744: добавление комиссии к заказу

---

local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly/basket_items.php
local/templates/aspro_kshop_copy/components/bitrix/sale.basket.basket/fly/template.php

доработка скрипта по отработке нажатия кнопки "Продолжить покупки" из блока "плавающей" корзины

SUP-5773: доработка скрипта по отработке нажатия кнопки "Продолжить покупки"

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/style.css
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php

SUP-5744: правки по заказу

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/template.php

SUP-5744: уделение дебага

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php

правки по логике вывода наценки

SUP-5744: правки по логике вывода наценки

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php

SUP-5744: правки логики расчета наценки

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php

SUP-5744: правки расчета

---

local/php_interface/init.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/confirm.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/delivery.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/paysystem.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/props_format.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/template.php
local/templates/aspro_kshop_copy/components/bitrix/system.auth.form/main_order/template.php

правка регистрации пользователя

SUP-5745 правка регистрации пользователя

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/confirm.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/props_format.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/template.php

SUP-5745: правка регистрации

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/template.php

правка оформления заказа при регистрации пользователя

SUP-5745: правка оформления заказа при регистрации пользователя

---

local/php_interface/init.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/delivery.php
local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/lang/ru/template.php

SUP-5891: правки суммы доставки

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/summary.php

правки суммы при формировании комплектов и планов

SUP-5941: правки суммы при формировании комплектов и планов

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/summary.php

SUP-5975: вывод скидки в рублях

---

local/templates/aspro_kshop_copy/components/bitrix/sale.order.ajax/main/style.css

SUP-5976: правка стилей заказа

---

local/templates/.default/components/bitrix/sale.order.ajax/order_make_location_2.0/summary.php

SUP-5941: правка стилей в заказе
